# -*- coding: utf-8 -*-
"""Simple nn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOsB4wOL4AlmteD47jq8zFRmXhfBeX_9
"""

import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

X = torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y = torch.tensor([[0.],[1.],[1.],[0.]])